<a href="https://colab.research.google.com/github/Garvish47/Cognitive_computing/blob/main/102317190_garvish_assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Q1)

In [2]:
arr = np.array([1, 2, 3, 4, 5])

arr_add = arr + 2
print("Array after adding 2 to each element:", arr_add)

arr_multiply = arr * 3
print("Array after multiplying each element by 3:", arr_multiply)

arr_divide = arr / 2
print("Array after dividing each element by 2:", arr_divide)

Array after adding 2 to each element: [3 4 5 6 7]
Array after multiplying each element by 3: [ 3  6  9 12 15]
Array after dividing each element by 2: [0.5 1.  1.5 2.  2.5]


Q2) a)

In [6]:
arr = np.array([1, 2, 3, 6, 4, 5])

arr_reversed = arr[::-1]
print("Reversed array:", arr_reversed)

Reversed array: [5 4 6 3 2 1]


b) i)

In [7]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

indices_x = np.where(x == most_frequent_value)[0]

print("Most frequent value:", most_frequent_value)
print("Indices of the most frequent value:", indices_x)

Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]


In [9]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

unique_y, counts_y = np.unique(y, return_counts=True)
most_frequent_value_y = unique_y[np.argmax(counts_y)]

indices_y = np.where(y == most_frequent_value_y)[0]

print("Most frequent value:", most_frequent_value_y)
print("Indices of the most frequent value:", indices_y)

Most frequent value: 1
Indices of the most frequent value: [0 1 2]


In [11]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

#a)
element_1st_row_2nd_column = arr[0, 1]
print("1st row, 2nd column element:", element_1st_row_2nd_column)

#b)
element_3rd_row_1st_column = arr[2, 0]
print("3rd row, 1st column element:", element_3rd_row_1st_column)

1st row, 2nd column element: 20
3rd row, 1st column element: 70


In [17]:
garvish = np.linspace(10, 100, 25)

print(garvish)


print("Dimensions of the array:", garvish.ndim)

print("Shape of the array:", garvish.shape)

print("Total number of elements:", garvish.size)

print("Data type of elements:", garvish.dtype)

print("Total number of bytes consumed:", garvish.nbytes)

transpose_reshape = garvish.reshape(-1, 1)
print("Transpose using reshape():", transpose_reshape)

transpose_T = garvish.T
print("Transpose using T attribute:", transpose_T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements: 25
Data type of elements: float64
Total number of bytes consumed: 200
Transpose using reshape(): [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [23]:
import numpy as np

ucs420_garvish = np.array([[10, 20, 30, 40],
                           [50, 60, 70, 80],
                           [90, 15, 20, 35]])

print("Original array (ucs420_garvish):")
print(ucs420_garvish)

print("\nMean:", np.mean(ucs420_garvish))
print("Median:", np.median(ucs420_garvish))
print("Max:", np.max(ucs420_garvish))
print("Min:", np.min(ucs420_garvish))
print("Unique elements:", np.unique(ucs420_garvish))

reshaped_ucs420_garvish = np.reshape(ucs420_garvish, (4, 3))
print("\nReshaped array (reshaped_ucs420_garvish):")
print(reshaped_ucs420_garvish)

resized_ucs420_garvish = np.resize(ucs420_garvish, (2, 3))
print("\nResized array (resized_ucs420_garvish):")
print(resized_ucs420_garvish)

Original array (ucs420_garvish):
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (reshaped_ucs420_garvish):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (resized_ucs420_garvish):
[[10 20 30]
 [40 50 60]]
